package org.android.turnaround.util.dialog

enum class WarningType {
    WARNING_DELETE_ACTIVITY,
    WARNING_CANCEL_ACTIVITY,
    WARNING_TAKE_PHOTO_AGAIN,
    WARNING_SKIP_REVIEW,
    WARNING_CANCEL_REVIEW,
    WARNING_WITHDRAW,
    WARNING_NOTIFICATION,
    WARNING_DUPLICATE_LOGIN
}
